LPD-40375 Allow Basic CRUD operations of a Display Page Templates Folder - delete, get and post
liferay-page-management/liferay-portal pull request #16487
Opened 2024-10-30 15:10 UTC by BarbaraCabrera

## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPD-40375)

### Changes

Add the basic operations (delete, get and post) for the Display Page Templates Folders.

## How to test it

1. Create a Display Page Template Folder
2. Go to [http://localhost:8080/o/api?endpoint=http://localhost:8080/o/headless-admin-site/v1.0/openapi.json](http://localhost:8080/o/api?endpoint=http://localhost:8080/o/headless-admin-site/v1.0/openapi.json)
3. Test the Get using the `siteExternalReferenceCode`and the `displayPageTemplateFolderExternalReferenceCode`. Copy the response to use it in the Post operation.
4. Test the Delete using the same information, the `siteExternalReferenceCode`and the `displayPageTemplateFolderExternalReferenceCode`
5. Test the Post with the information obtained in the step 3.

2024-10-30 15:10 UTC, liferay-page-management commented
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

2024-10-30 15:10 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-10-30 15:14 UTC, BarbaraCabrera commented
ci:test:sf

2024-10-30 15:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-source-format/5889/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/5889/jenkins-report.html">here</a>.</b></p>

2024-10-30 15:21 UTC, BarbaraCabrera commented
ci:test:relevant

2024-10-30 15:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-9.liferay.com/job/test-portal-source-format/5889/">test-portal-source-format#5889</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/5889/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-page-management/liferay-portal/pull/16487">liferay-page-management#16487</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/56217853">[master] ci:test:sf - BarbaraCabrera &gt; liferay-page-management - PR#16487 - 2024-10-30[08:14:35]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>56217853<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-9.liferay.com/job/publish-testray-report/6639/">publish-testray-report#6639</a><br/></div></div>

2024-10-30 17:52 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 24 out of 24 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 45 out of 45 jobs passed in 2 hours 31 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bc425dc709b850edaeaa392147145955720664a6">bc425dc709b850edaeaa392147145955720664a6</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d0b52765d46d39352692ddccd7138acdd8e06866">d0b52765d46d39352692ddccd7138acdd8e06866</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/35392/routines/590307/build/55915318">EE Development Acceptance (master) - 963 - 2024-10-29[22:01:57]</a></p><details><summary><strong>ci:test:stable - 24 out of 24 jobs PASSED</strong></summary><details><summary><strong>24 Successful Jobs:</strong></summary><ul><li>central-requirements<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1077797/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/439541/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/388009/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/442093/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/378835/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/456417/">js-unit/0/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/375107/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/482159/">modules-compile/0/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/439544/">modules-compile/0/1</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/485444/">modules-compile/0/2</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/433544/">modules-compile/0/3</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/388008/">modules-compile/0/4</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/375119/">modules-compile/0/5</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/485442/">modules-compile/0/6</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/439542/">modules-compile/0/7</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/442092/">modules-compile/0/8</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/433543/">modules-compile/0/9</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/442091/">modules-compile/0/10</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/485443/">modules-compile/0/11</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/439543/">modules-compile/0/12</a></li></ul></li><li>modules-integration-mysql57_stable<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/971188/">modules-integration-mysql57_stable/0/0</a></li></ul></li><li>modules-unit_stable<ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/433542/">modules-unit_stable/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57_stable<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/375118/">playwright-js-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>unit_stable<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/388007/">unit_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 45 out of 45 jobs PASSED</strong></summary><details><summary><strong>45 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/14120/">test-portal-acceptance-pullrequest(master)</a></li><li>central-requirements<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1077797/">central-requirements/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57_stable<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/439541/">functional-smoke-tomcat90-mysql57_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57_stable<ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/388009/">functional-upgrade-tomcat90-mysql57_stable/0/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/442093/">functional-upgrade-tomcat90-mysql57_stable/0/1</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/378835/">functional-upgrade-tomcat90-mysql57_stable/0/2</a></li></ul></li><li>js-unit<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/456417/">js-unit/0/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/375107/">js-unit/1/0</a></li></ul></li><li>modules-compile<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/482159/">modules-compile/0/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/439544/">modules-compile/0/1</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/485444/">modules-compile/0/2</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/433544/">modules-compile/0/3</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/388008/">modules-compile/0/4</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/375119/">modules-compile/0/5</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/485442/">modules-compile/0/6</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/439542/">modules-compile/0/7</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/442092/">modules-compile/0/8</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/433543/">modules-compile/0/9</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/442091/">modules-compile/0/10</a></li><li><a href="https://test-1-8.liferay.com/job/test [...]

2024-10-30 17:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/14120/">test-portal-acceptance-pullrequest(master)#14120</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/14120/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-page-management/liferay-portal/pull/16487">liferay-page-management#16487</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/56255345">[master] ci:test:relevant - BarbaraCabrera &gt; liferay-page-management - PR#16487 - 2024-10-30[08:21:22]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>56255345<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/32866/">publish-testray-report#32866</a><br/></div></div>

2024-10-30 23:27 UTC, ruben-pulido requested changes

2024-10-30 23:27 UTC, ruben-pulido commented on modules/apps/headless/headless-admin-site/headless-admin-site-test/src/testIntegration/java/com/liferay/headless/admin/site/resource/v1_0/test/DisplayPageTemplateFolderResourceTest.java
> +	}
We should keep these in sync with the fields that we are setting in the converter and specifying when creating/updatinga new entity. so they are also tested. For example, if we are setting externalReferenceCode, we should include it here, so it is verified by the tests.

2024-11-04 02:30 UTC, BarbaraCabrera commented
Hi, @ruben-pulido ! 😄 

After taking into consideration your comments I tried to use the external reference code instead of the id, but the main problem has come with the differences between the Display Page Template Folder (DPTF) and the Layout Page Template Collection (LPTC) entities. I can add the parent ERC to the DPTF, but the LPTC only have the parent Id, so every time I need to use the service I have to use the parent ERC to get the parent and then its id.

The thing is that when we can't find a collection with that parent external reference code, 

>`_layoutPageTemplateCollectionService.fetchLayoutPageTemplateCollection(parentDisplayPageTemplateFolderExternalReferenceCode, group.getGroupId()) == null`

I need to use the `PARENT_LAYOUT_PAGE_TEMPLATE_COLLECTION_ID_DEFAULT` but that "default collection" doesn't have an ERC because it's not a collection, it's just the parent id that we use to know that it doesn't really have a parent and that it's at the main level. So it means that I have to add null for the parent ERC and if we look at the validations that are generated:

<img width="642" alt="image" src="https://github.com/user-attachments/assets/e9902d7f-beaf-46e8-a6fc-b90763c46465">
 
That's not possible.

So the best solutions I can think of it's allow a parent ERC null (in the validations) or add an ERC for the default parent or leave the id.

I hope I explained it well, let me know what you think and thank you in advance! 🤓

2024-11-04 12:48 UTC, ruben-pulido commented
https://github.com/liferay-page-management/liferay-portal/pull/16509

2024-11-04 12:48 UTC, closed without merging